### ISSUE TITLE
Добавить возможность определять измененные блоки

### ISSUE THREAD

**Issue by lgordey** [typograf/typograf#155]
Сейчас можно скормить типографу абзац текста, и он вернет абзац с некоторыми изменениями.

Было бы здорово, если бы он мог еще возвращать конкретные куски, которые он заменил.
С помощью это можно будет построить дифф изменений, как в гите.

**Comment by hcodes** [comment]
Было бы круто :)
Это можно использовать в линтере, например, но придётся переписать все правила.

**Comment by kobezzza** [comment]
Не проще ли использовать для таких задач отдельно инструмент дифер, коих на JS написано вагон уже. Всё такие Unix-way :smile: 

https://www.npmjs.com/search?q=diff

**Comment by lgordey** [comment]
Проще, но диффер - это еще одна зависимость в проект и лишняя итерация.
А т.к. типограф парсит текст по конкретному списку правил, то он мог бы отдавать дифф по каждому правилу, это было бы менее затратно.

**Comment by hcodes** [comment]
Прикрутил [diff](https://www.npmjs.com/package/diff) к [typograf.github.io](https://typograf.github.io).

CSS:

``` css
del.diff
{
    text-decoration: none;

    color: #b30000;
    background: #fadad7;
}

ins.diff
{
    text-decoration: none;

    color: #406619;
    background: #eaf2c2;
}
```

JS:

``` js
var JsDiff = require('diff');

function myDiff(oldText, newText) {
        var diff = JsDiff.diffChars(oldText, newText),
            html = '';

        diff.forEach(function(part){
            var val = str.escapeHTML(part.value);
            if(part.added) {
                html += '<ins class="diff">' + val + '</ins>';
            } else if(part.removed) {
                html += '<del class="diff">' + val + '</del>';
            } else {
                html += val;
            }
        }, this);

        return html;
}
```
